package net.sf.xplanner.domain;

// Generated 16-Nov-2009 23:34:52 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AttributeId generated by hbm2java.
 */
@Embeddable
public class AttributeId implements java.io.Serializable {

	/** The target id. */
	private int targetId;
	
	/** The name. */
	private String name;

	/**
     * Instantiates a new attribute id.
     */
	public AttributeId() {
	}

	/**
     * Instantiates a new attribute id.
     *
     * @param targetId
     *            the target id
     * @param name
     *            the name
     */
	public AttributeId(final int targetId, final String name) {
		this.targetId = targetId;
		this.name = name;
	}

	/**
     * Gets the target id.
     *
     * @return the target id
     */
	@Column(name = "targetId", nullable = false)
	public int getTargetId() {
		return this.targetId;
	}

	/**
     * Sets the target id.
     *
     * @param targetId
     *            the new target id
     */
	public void setTargetId(final int targetId) {
		this.targetId = targetId;
	}

	/**
     * Gets the name.
     *
     * @return the name
     */
	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	/**
     * Sets the name.
     *
     * @param name
     *            the new name
     */
	public void setName(final String name) {
		this.name = name;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(final Object other) {
		if (this == other) {
			return true;
		}
		if (other == null) {
			return false;
		}
		if (!(other instanceof AttributeId)) {
			return false;
		}
		final AttributeId castOther = (AttributeId) other;

		return this.getTargetId() == castOther.getTargetId()
				&& (this.getName() == castOther.getName() || this.getName() != null
						&& castOther.getName() != null
						&& this.getName().equals(castOther.getName()));
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTargetId();
		result = 37 * result
				+ (this.getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
